// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package watchmock is a generated GoMock package.
package watchmock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	evdev "github.com/hareku/evdev-trigger/pkg/evdev"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHandler) Do(ctx context.Context, ev *evdev.InputEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Do", ctx, ev)
}

// Do indicates an expected call of Do.
func (mr *MockHandlerMockRecorder) Do(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHandler)(nil).Do), ctx, ev)
}
