// Code generated by MockGen. DO NOT EDIT.
// Source: finder.go

// Package evdevmock is a generated GoMock package.
package evdevmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	evdev "github.com/hareku/evdev-trigger/pkg/evdev"
)

// MockFinder is a mock of Finder interface.
type MockFinder struct {
	ctrl     *gomock.Controller
	recorder *MockFinderMockRecorder
}

// MockFinderMockRecorder is the mock recorder for MockFinder.
type MockFinderMockRecorder struct {
	mock *MockFinder
}

// NewMockFinder creates a new mock instance.
func NewMockFinder(ctrl *gomock.Controller) *MockFinder {
	mock := &MockFinder{ctrl: ctrl}
	mock.recorder = &MockFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinder) EXPECT() *MockFinderMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockFinder) Find(phys string) (evdev.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", phys)
	ret0, _ := ret[0].(evdev.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockFinderMockRecorder) Find(phys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockFinder)(nil).Find), phys)
}
